INSERT INTO autor (nome)
VALUES ('J. K. Rowling'),
       ('George R. R. Martin'),
       ('J. R. R. Tolkien'),
       ('Isaac Asimov'),
       ('Stephen King'),
       ('Agatha Christie'),
       ('Neil Gaiman'),
       ('Terry Pratchett'),
       ('Arthur C. Clarke'),
       ('H. P. Lovecraft'),
       ('Dan Brown'),
       ('Ernest Hemingway'),
       ('Jane Austen'),
       ('Mark Twain'),
       ('Charles Dickens'),
       ('Fiódor Dostoiévski'),
       ('Gabriel García Márquez'),
       ('Jules Verne'),
       ('Oscar Wilde'),
       ('Virginia Woolf');
INSERT INTO genero (nome)
VALUES ('Fantasia'),
       ('Ficção Científica'),
       ('Terror'),
       ('Mistério'),
       ('Romance'),
       ('Drama'),
       ('Aventura'),
       ('Histórico'),
       ('Suspense'),
       ('Filosofia');
INSERT INTO livro (titulo, autor_id, genero_id)
VALUES ('Harry Potter e a Pedra Filosofal', 1, 1),
       ('Harry Potter e a Câmara Secreta', 1, 1),
       ('As Crônicas de Gelo e Fogo', 2, 1),
       ('O Senhor dos Anéis', 3, 1),
       ('Fundação', 4, 2),
       ('Eu Sou a Lenda', 5, 3),
       ('Assassinato no Expresso Oriente', 6, 4),
       ('Deuses Americanos', 7, 1),
       ('Good Omens', 8, 1),
       ('2001: Uma Odisseia no Espaço', 9, 2),
       ('O Chamado de Cthulhu', 10, 3),
       ('O Código Da Vinci', 11, 4),
       ('O Velho e o Mar', 12, 6),
       ('Orgulho e Preconceito', 13, 5),
       ('As Aventuras de Tom Sawyer', 14, 7),
       ('Oliver Twist', 15, 8),
       ('Crime e Castigo', 16, 9),
       ('Cem Anos de Solidão', 17, 6),
       ('Vinte Mil Léguas Submarinas', 18, 2),
       ('O Retrato de Dorian Gray', 19, 5),
       ('Mrs. Dalloway', 20, 6);